### ISSUE TITLE
Build and installation instructions

### ISSUE THREAD

**Issue by hcayless** [Conal-Tuohy/jEdit-TEIPlugin#13]
Hi Conal,

I'm not sure where to start in testing the plugin—it won't build out as is, probably because I need to specify some environment variables. But I'm not certain what those settings need to be. A brief INSTALL.md would be super helpful.

**Comment by Conal-Tuohy** [comment]
Hi Hugh!

I will update this later this week, but for now may I suggest you try testing the pre-built release. 

The issue with the build setup is complicated; I'm hoping to have something which conforms to standard practice for jEdit plugin builds, but it's a bit up in the air.

**Comment by Conal-Tuohy** [comment]
For now (i.e. until the TEI plugin is published through the jEdit Plugin Central repository), you will need to copy the TEI.jar file into jEdit's "jars" folder. You'll also need to have first installed the Saxon plugin and the XML plugin (using the standard installation for jEdit plugins, i.e. from the Plugins menu).

**Comment by Conal-Tuohy** [comment]
I ended up revising the build script to eliminate the dependency on the jEdit community's "build-support" Ant script, because that script brought further complications with it. The build script is now a bit longer, but it is self-contained and doesn't depend on any environment variables or external tools (barring Apache Ant itself). 

I thought this was best because I wanted to make the build maximally accessible to developers in the TEI community who in general will not know anything about conventional practices in building jEdit plugins. I know I didn't! And if I hadn't had to, I'd have preferred to remain ignorant, to be perfectly honest.

It's now possible to build the TEI.jar file using Apache Ant by cloning the repo and issuing the command:

`ant`

That creates the `TEI.jar` file in the `dist` folder, which you can then install and test by copying it to jEdit's `jars` folder (whose location will depend on your OS, see http://plugins.jedit.org/install.php for details)
